name: Print Current Directory

on:
  push:
    branches: [ main ]

jobs:
  print-directory:
    runs-on: windows-latest
    steps:
      - name: Print current working directory
        run: |
          echo Current directory is test1 %GITHUB_WORKSPACE% test2 $env:GITHUB_WORKSPACE
